name: CI for assignment

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
        uses: actions/checkout@v3

        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        env:
          FLASK_ENV: testing
          FLASK_APP: app
        run: pytest